
spring:
  datasource:
    url: jdbc:h2:mem:testdb
#    url=jdbc:h2:file:/data/sampledata
#    url=jdbc:h2:C:/data/sampledata
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
