DROP TABLE IF EXISTS AUTHORIZATION;
CREATE TABLE AUTHORIZATION (
    AUTHORIZATION_ID INT AUTO_INCREMENT  PRIMARY KEY,
    ACCOUNT_ID INT,
    REF_NUMBER INT,
    AMOUNT INT,
    AUHTORIZATION_TEXT CLOB(10K)
);